### PR TITLE
Profile Page added

### LINKED ISSUE #33: Create profile page

### PR DESCRIPTION
**Pull request by Darshilp326**
Screenshot (146)
Screenshot (147)

### CODE REVIEW

**Comment by MananDesai54** [comment]
can you make the background colors same as before ? this is fine but it will not match with other pages @Darshilp326

**Comment by Darshilp326** [comment]
@MananDesai54  I have changed navbar background color. So it would be same in whole project.

**Comment by MananDesai54** [comment]
Okay then no issues 👍@Darshilp326

**Comment by dkp1903** [comment]
give @Darshilp326 25 points

**Pull request merged**
